students=("aarav","rohan","meera","kabir","isha","vikram","diya")
print("part A")
print(students)
print("1.",len(students))
print("2.print the first student:",students[0])
print("3.print the fourth student:",students[3])
print("4.print the first 3 students:",students[0:4])
print("5.print the students:",students[2:6])
print("part B")
print("6.print the last student:",students[-1])
print("7.print the second last student:",students[-2])
print("8.print the last 3 students:",students[-1:-3])
print("9.print the first and last student:",students[-7:])